name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  cache-dependencies:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 8
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        # perfect match for the cache key:
        # if a POM changes we start with a brand new cache
    - name: Download Maven dependencies
      run: >
        mvn -f io.github.lorenzobettini.example.parent/pom.xml
        -Pjacoco dependency:go-offline

  build:
    needs: cache-dependencies
    strategy:
      matrix:
        # test against several OSes:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # test against several Java versions:
        java: [ 8, 11 ]
        # excludes JDK 11 on macOS and Windows
        exclude:
        - os: macos-latest
          java: 11
        - os: windows-latest
          java: 11
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.6.0
      with:
        java-version: ${{ matrix.java }}
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      id: m2cache # note the cache id, see below for cache-hit
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-build-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Set Maven offline option
      run: |
        echo "maven_arguments='--offline'" >> $GITHUB_ENV
      if: steps.m2cache.outputs.cache-hit == 'true' # note the use of the id 'm2cache'
    - name: Build with Maven
      run: >
        mvn -f io.github.lorenzobettini.example.parent/pom.xml
        -Pjacoco verify
        ${{ env.maven_arguments }}
